apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: elasticsearch-operator
  namespace: openshift-operators 
spec:
  channel: "4.5"
  name: elasticsearch-operator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jaeger-product
  namespace: openshift-operators 
spec:
  channel: stable
  name: jaeger-product
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: kiali-ossm 
  namespace: openshift-operators 
spec:
  channel: stable
  name: kiali-ossm
  source: redhat-operators 
  sourceNamespace: openshift-marketplace


---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: servicemeshoperator
  namespace: openshift-operators 
spec:
  channel: stable
  name: servicemeshoperator
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 


---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: amq-streams
  namespace: openshift-operators 
spec:
  channel: stable
  name: amq-streams
  source: redhat-operators 
  sourceNamespace: openshift-marketplace 

---
apiVersion: operators.coreos.com/v1
kind: OperatorGroup
metadata:
  name: courie-pipeline-og
  namespace: courie-pipeline
spec:
  targetNamespaces:
  - courie-pipeline

---
apiVersion: operators.coreos.com/v1alpha1
kind: Subscription
metadata:
  name: jenkins-operator
  namespace: courie-pipeline
spec:
  channel: alpha
  name: jenkins-operator
  source: community-operators
  sourceNamespace: openshift-marketplace 

